services:
  frontend:
    image: node:alpine
    container_name: frontend
    ports:
      - 80:8000
    command: "./setup.sh"
    working_dir: /srv/app
    volumes:
      - ./frontend:/srv/app
      - /srv/app/node_modules
    tty: true

  backend:
    image: node:alpine
    container_name: backend
    ports:
      - 81:3000
    command: "./setup.sh"
    working_dir: /srv/app
    volumes:
      - ./employee-fe:/srv/app
    # - /srv/app/node_modules
    tty: true

  database:
    image: mongo:6-jammy
    container_name: database
    ports:
      - 27017:27017
    volumes:
      - dbdata6:/data/db

volumes:
  dbdata6: